#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-2.0+
#
# net-setup.sh — apply IP / route / DNS from a connected ModemManager bearer.
#
# Source this file from mmcli.sh. Reads bearer fields via mmcli-parser.sh's
# get_bearer_field(), then brings up the qmapmux* interface with the carrier-
# supplied addresses.

set -euo pipefail

configure_ip_route_dns() {
    local bearer_path="$1"

    local interface address prefix gateway dns mtu
    interface="$(get_bearer_field "${bearer_path}" interface)"
    address="$(get_bearer_field "${bearer_path}" address)"
    prefix="$(get_bearer_field "${bearer_path}" prefix)"
    gateway="$(get_bearer_field "${bearer_path}" gateway)"
    dns="$(get_bearer_field "${bearer_path}" dns)"
    mtu="$(get_bearer_field "${bearer_path}" mtu)"

    if [[ -z "${interface}" || -z "${address}" || -z "${prefix}" ]]; then
        echo "configure_ip_route_dns: incomplete bearer info" >&2
        return 1
    fi

    ip addr flush dev "${interface}"
    ip link set "${interface}" up mtu "${mtu}"
    ip addr add "${address}/${prefix}" dev "${interface}"
    ip route add default via "${gateway}" dev "${interface}"

    configure_dns "${interface}" "${dns}"
}

configure_dns() {
    local interface="$1"
    local dns_csv="$2"

    [[ -z "${dns_csv}" ]] && return 0

    local dns_servers
    dns_servers="$(printf '%s' "${dns_csv}" | tr ',' ' ' | xargs)"

    if command -v resolvectl >/dev/null 2>&1; then
        # systemd-resolved branch
        # shellcheck disable=SC2086
        resolvectl dns "${interface}" ${dns_servers}
        resolvectl domain "${interface}" '~.'
        resolvectl default-route "${interface}" yes
    else
        # Legacy /etc/resolv.conf branch
        {
            echo "# Generated by quectel-mm-throughput runtime/mmcli.sh"
            for ns in ${dns_servers}; do
                echo "nameserver ${ns}"
            done
        } > /etc/resolv.conf
    fi
}